language: node_js
node_js:
  - 11
cache:
  yarn: true  
branches:
  only:
    - master
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.2
  - export PATH="$HOME/.yarn/bin:$PATH"    
script:
  - yarn docz:deploy    
