language: node_js
node_js:
  - 11
branches:
  only:
    - master
before_install:
  - git remote set-url origin https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/xendora/react-timer.git
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true
script:
  - yarn docz:deploy    
